os: linux
sudo: false

language:
  - java

jdk:
  - oraclejdk7

cache:
  directories:
    - $HOME/.m2

git:
  depth: 500

branches:
  only:
    - master
    - /^release.*$/
    - coverity_scan

env:
  global:
    - secure: "HLsGCBxdW7zCX7UCAPZsAgeWpCB0waxz2ePUPhNTIt5ywbm4VDYo0uRm65W/Vht9Wd9pwvO/NBxEwyptQWih2aOXwBd02i63kLYMczoWhGn0SRsHpkhRYuF/pbbRyKoM9BWBrsMF0bBz1y5Q5VPzhnd3DMUK1tx5QTO4Qtbs68k="
    - secure: "bPaiv55l7/hayD0vJe4xVfK+cXTICjfJ+hfz9gDDcyEqEXfosVguOS8Q3COzkmHxjU9yEv9vrxJWyaKBdOUr5FoEIk3UlCnbD0pH21OzT22bJXLl/LZ9biIcmzX37a8XwOS0eDWsyAmLM6vG4OcRu4azd4x42mffsT7T5208DFg="
    # Coverity Scan Token
    - secure: "Qwgm1E4rVWsRUd1hNaZ8xIkf/tX9zTkR5T5JtB3K+3kqKWp2dJ51m9rhlNR+pMF9/+zaWnPJRz2Oah1Bs3FHMA6f1qzU4h8nWW7jGal1g/yz9oPzBe2kaxnBalrbbP9OQWC8hAN/oYehCTth4N5IOBvlqVHnq6+jqLJr9mmElec="

before_install:
  # ugly hack; if running a coverity scan abort all except the 1st build
  # see note re gcc compiler above needing to be 1st
  # also note that branch_pattern & the TRAVIS_BRANCH check must match
  # unfortunately COVERITY_SCAN_BRANCH isn't defined until later in the
  # build process
  - if ([[ "${TRAVIS_JOB_NUMBER##*.}" != "1" ]] && [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]); then false; fi
  - pip install --user codecov

install:
  - jdk_switcher use oraclejdk7 && export JAVA7_HOME=$JAVA_HOME
  - jdk_switcher use oraclejdk8 && export JAVA8_HOME=$JAVA_HOME
#  - mvn clean compile dependency:resolve --quiet -U -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./build.sh; fi

after_success:
  - codecov
  - test "${COVERITY_SCAN_BRANCH}" == 1 && mvn coverity-ondemand:check

matrix:
  fast_finish: true

addons:
  coverity_scan:
    project:
      name: "pawelprazak/java-extended"
      description: "Coverity via Travis CI"

    notification_email: "pawel@bluecatcode.com"

    build_command: "mvn test -Pbuild-test -B"

    # must match TRAVIS_BRANCH check below
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

